In [1]:
from scipy import constants
from astropy import units as u
import numpy as np 

# Toomre's Q parameter

## Us

In [ ]:
r=150*u.au
M_star = 0.41*u.solMass
M_disk = 0.22*u.solMass
T=100*u.K #disk temperature

In [ ]:
r=300*u.au

## Tobin (HOPS 370)

In [ ]:
r=50*u.au
M_star = 2.5*u.solMass
M_disk = 0.06*u.solMass
T=180*u.K #disk temperature

In [ ]:
G = constants.G * u.m**3 * u.kg**(-1) * u.s**(-2) #Gravitatcional constant
gamma=7/5 #adiabatic index, 7/5 for a diatomic gas and 5/3 for a monoatomic
k = constants.k * u.kg * u.m**2 * u.s**(-2) * u.K**(-1) #Boltzmann constant 
m_H2 = 2*1.00794*u.u #molecular mass (H_2)
#cs = (gamma*k*T/mH2.to(u.kg))**(1/2) #disk sound speed
cs=560*u.m*u.s**(-1)
v = np.sqrt(G*M_star.to(u.kg)/r.to(u.m)) #linear velocity at radius r
w = v/r.to(u.m) #Keplerian angular velocity
H = cs/w # disk scale height
Q = 2*M_star/M_disk * H/r.to(u.m) #(for a rotationally supported disk around a protostar, Kratter & Lodato 2016, Tobin 2016)
print(Q)

# From dust emission

## M (dust)

In [3]:
S = 1102#en mJy
D = 300# en pc
k_nu = 1.77 #en cm^2/g (del polvo)
f= 100 # gas-to-dust ratio
T_d = np.array([126-23,126,126+23]) #en K (126+-23K)
M_d=5.3e-3*(S/10)*(D/140)**2*(k_nu/f/0.01)**(-1)*(T_d/15)**(-1) #en solar mass (del gas)
print(M_d)

[0.22066054 0.18038123 0.15253715]


## Calculo N(H2)

In [5]:
d_d=2 #diameter in arcsec
r_d=d_d/2*D*u.au #radio in AU 
A_d=np.pi*(r_d.to(u.cm))**2 #area of the disk
m_H2 = 2*1.00794*u.u #molecular mass (H_2)
N_H2_d=M_d*u.M_sun/(A_d*m_H2.to(u.M_sun)) 
print(N_H2_d)

[2.07144593e+24 1.69332484e+24 1.43193913e+24] 1 / cm2


## Calculo abundancia

In [6]:
N_Sp_d = 3.9e14*u.cm**(-2) #column density of the species
Ab_Sp_d = N_Sp_d/N_H2_d #abundance of the species with respect to H2
print(Ab_Sp_d)

[1.88274285e-10 2.30316115e-10 2.72357946e-10]


# From line emission

## M

In [11]:
d_l=0.6 #diameter in arcsec
D=300 #distance in pc
N_Sp = 3.9e14*u.cm**(-2) #column density of the species
Frac_Ab_Sp = 1/45#fractional abundance of the species (13C/12C=1/45, 15N/14N=1/234 Crocket 2014 -> Tercero 2010)
Ab_Mol = 4.1e-9 #abundance of the molecule respect to H2 (HCN=3.8e-7 hot core, 4.1e-9 compact ridge, 2.8e-7 plateu, 3.3e-8 extendend ridge, Crocket 2014)
Ab_Sp = Frac_Ab_Sp * Ab_Mol #abundance of the species with respect to H2
r_l=d_l/2*D*u.au #radio in AU 
A_l=np.pi*(r_l.to(u.cm))**2 #area of the disk
m_H2 = 2*1.00794*u.u #molecular mass (H_2)
N_H2_l = N_Sp/Ab_Sp
M_H2_l = A_l*N_H2_l*m_H2.to(u.M_sun)
M_H2=M_H2_l*(r_d/r_l)**2
print(Ab_Sp)
print(N_H2_l)
print(M_H2_l)
print(M_H2)

9.111111111111112e-11
4.2804878048780483e+24 1 / cm2
0.04103806197386875 solMass
0.4559784663763195 solMass
